font_family JetBrainsMono Nerd Font
font_size 11.0
enable_audio_bell no
linux_display_server wayland
window_padding_width 10
background #0d0d0d
foreground #dedede
background_opacity 0.94
selection_background #3b3b3b
selection_foreground #dedede
cursor #bcbcbc
url_color #bcbcbc
color0 #181818
color1 #c9c9c9
color2 #adadad
color3 #d6d6d6
color4 #bcbcbc
color5 #a8a8a8
color6 #b7b7b7
color7 #dedede
color8 #999999
color9 #c9c9c9
color10 #adadad
color11 #d6d6d6
color12 #bcbcbc
color13 #a8a8a8
color14 #b7b7b7
color15 #dedede

