[Appearance]
style=kvantum
icon_theme=Graphite-Dark
standard_dialogs=default
custom_palette=false

[Fonts]
general="Inter Variable,10,-1,5,50,0,0,0,0,0"
fixed="JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0"
